project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

# Pattern App name
app_name = 'recipes'

# URLS do app recipes
urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/category/<int:category_id>/', views.category, name="category"),  # noqa E501
    path('recipe/<int:id>/', views.recipe, name="recipe"),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=100)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    @property
    def cover_url(self):
        if self.cover and hasattr(self.cover, 'url'):
            return self.cover.url

    def __str__(self) -> str:
        return self.title

recipes/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render

from recipes.models import Recipe


def home(request):
    recipes = Recipe.objects.filter(
        is_published=True,
    ).order_by('-id')

    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.filter(
        category__id=category_id,
        is_published=True
    ).order_by('-id'))

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes[0].category.name}'
    })


def recipe(request, id):
    recipe = get_object_or_404(Recipe.objects.filter(
        pk=id,
        is_published=True,
    ))

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block main_content %}
<div class="main-container__content main-container__list container">
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock main_content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home{% endblock title %}

{% block main_content %}
<div class="main-container__content main-container__list container">
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% empty %}
    <div class="center m-y">
        <h1>OPS! Nenhuma receita encontrada &#128554;</h1>
    </div>
    {% endfor %}
</div>
{% endblock main_content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}{{ recipe.title }}{% endblock title %}

{% block main_content %}
<div class="main-container__content main-container__detail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock main_content %}

recipes/templates/recipes/partials/footer.html
<footer class="footer-container">
    <div class="footer-container__content container">
        <div class="footer-container__developer">
            <a href="#" target="_blank" rel="noreferrer noopener">
                <span class="footer_text">By Abner Firmino</span>
            </a>
        </div>
        <div class="footer-container__powered">
            <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">
                <span class="footer_text">Powered by Django</span>
            </a>
        </div>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<!-- font awesome-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css" integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css" integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css" integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    
<!-- google Roboto Slab-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    
<link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">

recipes/templates/recipes/partials/header.html
<header class="header-container">
    <div class="header-container__content container">
        <h1>
            <a class="header-container__logo" href="{% url 'recipes:home' %}">
                <i class="fas fa-utensils header-container__icon"></i>
                <span class="header-container__text">Receitas</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe-list-item recipe">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <img src="{{ recipe.cover_url|default_if_none:'#' }}" />
        </a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author is not None %}
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            {% else %}
                Autor desconhecido
            {% endif %}
        </span>

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y"}} às {{ recipe.created_at|date:"H:i"}}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <br><i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
            <div class="recipe-meta-text">{{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}</div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porções</h3>
            <div class="recipe-meta-text">{{ recipe.servings }} {{ recipe.servings_unit }}</div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/recipes.html
<div class="recipe-list-item recipe">
    <div class="recipe-cover">
        <img src="https://via.placeholder.com/1280x720.png/269fe6" alt="Temporário">
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            Abner Firmino
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2022 às 11:21
        </span>
        <span class="recipe-author-item">
            <a href="/recipes/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
        </span>
    </div>

    <div class="recipe-content">
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta 
            quibusdam quod recusandae ipsa exercitationem minima dolorem, 
            nulla est sit iusto amet suscipit ut maiores. Ducimus sit 
            perspiciatis expedita ad incidunt.</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
            <div class="recipe-meta-text">0 Minuto(s)</div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porções</h3>
            <div class="recipe-meta-text">0 Porções</div>
        </div>
    </div>

    <footer class="recipe-footer">
        <a href="" class="recipe-read-more button button-dark">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="search-container__content">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>